name: create-staging

on:
    push:
        branches:
            - 'staging'
jobs:
    build:
        name: create-staging
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.1
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                
            - name: Setup Git Client
              run: |
                ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                git config --global user.email "github-actions@doesnotmatter.dev"
                git config --global user.name "GitHub Actions"
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3.0.3
              with:
                dotnet-version: 7.0.400
                # Authenticates packages to push to GPR
                source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
              env:
                NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

            - name: Install dependencies
              run: dotnet restore
              env:
                NUGET_AUTH_TOKEN: ${{ github.token }}
                  
            - name: Build
              run: dotnet publish me-academy.api --configuration Staging /p:EnvironmentName=Staging

            # Clone this repository (deploy-staging branch) inside the "deploy-staging" folder
            # Before clearing out, move .git folder out of the "deploy-staging" folder
            # Recreate deploy-staging folder, empty
            # Move .git folder back again
            # Move publish to deploy-staging folder
            # Push files to the "deploy-staging" branch
            - name: Deploy-Staging
              run: |
                git clone --depth 1 --single-branch -b deploy-staging git@github.com:${{ github.repository }}.git deploy-staging
                mv deploy-staging/.git deploy-staging-.git
                rm -rf deploy-staging
                mkdir deploy-staging
                mv deploy-staging-.git deploy-staging/.git
                cd deploy-staging
                cp -R ../me-academy.api/bin/Staging/net7.0/publish .
                git add .
                git diff --staged --quiet || git commit -m "Update Artifacts"
                git push
